version: '3.8'

services:
  email-forwarder-ui:
    build: .
    container_name: directadmin-fwd
    ports:
      - "5000:5000"
    environment:
      # User/Group IDs
      - PUID=1000
      - PGID=1000
      # Web UI Authentication
      - WEB_USERNAME=admin
      - WEB_PASSWORD=SecurePassword123!
      - SECRET_KEY=your-very-secret-key-change-this
      # DirectAdmin Configuration
      - DA_URL=https://your-directadmin-server.com:2222
      - DA_USER=your_admin_user
      - DA_PASS=your_admin_password
      - DA_DOMAIN=your-domain.com
    restart: unless-stopped
